### ISSUE TITLE
Purchase API Refactoring - Overview

### ISSUE THREAD

**Issue by negue** [HabitRPG/habitica#10011]
Goal:
- extract / abstract every purchasable operation into classes
- use a factory to get the needed class
- each operation has its own checks but also the inner checks for each currency-type
- checks to prevent bulk purchases on types that can't be purchased in bulk

Todo: 
- [x] Armoire [Gold] (#10153)
- [x] Market Gear [Gold] (#10010)
- [x] Health Potion [Gold] (#10152)
- [x] Quest [Gold] (#10244)
- [x] Buy Gem [Gold] (#10271)
- [x] Special Spell [Gold] (#10305)
- [x] Mount [Hourglass] (#10482)
- [ ] Pets [Hourglass]
- [x] Quest [Gem] (#10476)
- [ ] Mystery Set [Hourglass]
- [ ] Spell [Gem]
- [ ] Eggs [Gem]
- [ ] Hatching Potions [Gem]
- [ ] Food [Gem]
- [ ] Gear [Gem]
- [ ] Bundles [Gem]
- [ ] create / use factory
- [ ] fix / add new **TESTS!**

**Comment by seekheart** [comment]
@negue maybe time to move to typescript? It supports interfaces which may help with this

**Comment by negue** [comment]
Typescript would be nice yes, but we'd have a lot work before having a working server just with the typescript compiler instead of babel (atleast thats what I think)


Currently the classes are in ES6 so it would be already working with typescript

**Comment by seekheart** [comment]
It's not a whole lot more work though. Mostly we could put all the `client` code in to TS and just have typescript transpile it or gulp it?

**Comment by paglias** [comment]
I personally like Typescript but for now I'd say let's not introduce new tools :)

**Comment by TheHollidayInn** [comment]
Agreed. Typescript is something we can consider after we remove most of the code "smells"

**Comment by seekheart** [comment]
Are we following an OOP paradigm currently?

**Comment by paglias** [comment]
Is this still in progress?

**Comment by negue** [comment]
Not currently, no

**Comment by beffymaroo** [comment]
@negue Should I remove the in progress label from this issue, possibly add Help Wanted?
