### ISSUE TITLE
Enable MongoDB Transactions

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#12334]
Since https://github.com/HabitRPG/habitica/pull/12331 Habitica's codebase has been upgraded to use version 4.2 of MongoDB which also supports [transactions](https://docs.mongodb.com/manual/core/transactions/).

Due to the way transactions have been built into MongoDB it's not possible to start using them right away as they are only available on Replica Sets and not single node installations like our local installs.

This issue is about upgrading our current local development setup to use replica sets and make it possible to use transactions.

### Useful resources
- https://mongoosejs.com/docs/transactions.html
- https://github.com/vkarpov15/run-rs#readme

### Todo
- [x] Upgrade local installs to use a replica set
- [ ] run-rs seems to have problems with windows (first usage and hostname)
- [x] 1 node replica set?
- [x] Github actions https://github.com/vkarpov15/run-rs/issues/7 https://github.com/marketplace/actions/mongodb-in-github-actions
- [ ] Update docs
- [ ] Write an example on how to use transactions
- [x] locate issue that could be fixed once transactions are available
- [ ] locate blocks of code that might benefit from transactions
