### ISSUE TITLE
Part of the site doesn't use translated strings

### ISSUE THREAD

**Issue by Atomk** [HabitRPG/habitica#4522]
As the title says, I have found parts of the site using English strings even if there is a translated string available. I checked only the Italian translation but I am pretty sure that such problems can be found also in other languages (it's not the first time I discover these issues in the site).
What I've found till now:
1.  **[solved]** Backgrounds descriptions
2. **[solved]** "Subscribe" form
3.  **[solved]** Task progress
4. **[solved]** "Submit" button in Coupon page
5. **[solved]** "Press Kit" page _("Press Kit" in the navbar is still untranslated, the rest of the page is ok)_
6.  **[solved]** "Rewards" in quest scroll form (when purchasing one in the Market)
7. **[solved]** "Last updated" in Community guidelines
8. **[solved]** "Buy Gems" form (some string are already translated but not used)
9. **[solved]** Set names in "Time Travelers" page
   ![2015-03-22 12_13_16-greenshot](https://cloud.githubusercontent.com/assets/6122017/6769144/8050ca82-d08f-11e4-8dd6-a61166620416.png)
10. **[solved]** "Send gift" (in the form that pops up when you click on username label)
11. **[solved]** "Invite Friends" button (in "Members" section in guilds and party)
12. **[solved]** https://habitrpg.com/static/contact
##

**Comment by TheHollidayInn** [comment]
It seems that point 2 is fixed.

![screen shot 2015-03-02 at 5 53 01 pm](https://cloud.githubusercontent.com/assets/1253400/6453810/c885b624-c107-11e4-91db-74126a51745a.png)

I have created a pull request for number 4: https://github.com/HabitRPG/habitrpg/pull/4788 .

I'll be taking a look at number 5 now.

**Comment by Atomk** [comment]
@TheHollidayInn "Card", "Apply" and "Promo Code" translations are still missing in your screenshot, my fault, I should have marked it in the picture I uploaded. Thank you anyway!

**Comment by NotGonnaGitUs** [comment]
Added a pull request which fixes the following from the list
- 2. "Subscribe" form
- 4. "Submit" button in Coupon page
- 5. "Press Kit" page (Page Title)
- 7. "Last updated" in Community guidelines
- 8. "Buy Gems" form

**Comment by Atomk** [comment]
@NotGonnaGitUs I have just checked but only the 5 and part of the 8 seem to be fixed, maybe I need to wait for a site/translation update?

**Comment by NotGonnaGitUs** [comment]
Oh the pull request still hasn't been merged. Discussion is here - #5134 
I'll edit my comment for clarity.

**Comment by Atomk** [comment]
Ok, I'll wait for the merge and I'll make sure everything is fixed. Glad somebody cares about localizations!

**Comment by NotGonnaGitUs** [comment]
Hey, it has been merged into develop and should be live in the next iteration.

I am sure everyone here cares about localizations and thus, a better user experience. It is just that they are busy dealing with bigger monsters in the caverns of code. I will work on the remaining issues and try and fix them during the weekend.

**Comment by ghost** [comment]
**Solved**: The "Only group leader can create challenges" line on the
[guild creation page](https://habitrpg.com/#/options/groups/guilds/create) is not translatable. I've tried to address the issue in https://github.com/HabitRPG/habitrpg/pull/5178

**Comment by ghost** [comment]
**Messages in the front page Login / Register dialog**
I believe they are quite important, however they are not translatable. Is it possible to make the lines of auth.js translatable?

The lines in question include the following ones:

> `Uh-oh - your username or password is incorrect.\n- Make sure your username or email is typed correctly.\n- You may have signed up with Facebook, not email. Double-check by trying Facebook login.\n- If you forgot your password, click \"Forgot Password\"`
> 
> `Account has been suspended, please contact leslie@habitrpg.com with your UUID ('+uuid+') for assistance.`
> 
> `Email already taken`

[Screenshot](http://i.snag.gy/DQ4tD.jpg)
and so on... Some of the lines may be difficult to understand for someone who is only beginning to learn English.

**Comment by ghost** [comment]
STR, CON, PER, and INT in the equipment section of the stats page:
http://i.snag.gy/7nGcm.jpg

**Comment by ghost** [comment]
@Atomk 
_#10 is waiting to be merged.
_#11 is waiting to be merged - but it's actually not only a button, but a dialog also, I'm looking into it now to make another commit

**Comment by Atomk** [comment]
@NotGonnaGitUs I checked and now everything is ok! The coupon / promo code change could create some confusion, but I see you already discussed that with devs. Thanks anyway!

@GitHubSphinx Thanks for the info, I'll make sure to check when everything is ready. Should I add your comments to the list of missing translations? I don't know if it's better to keep everything in this issue or create another one (some time ago for another problem in the site I was suggested to create a new issue for every single thing...).

**Comment by ghost** [comment]
The dialog seems ready to me with https://github.com/GitHubSphinx/habitrpg/commit/fe2e0618b8d254b2ada03cce33c2ea60319e71b2

@Atomk IDK what's best. We used to have an all-in-one ticket https://github.com/HabitRPG/habitrpg/issues/3168 and we used to have some separate tickets for missed out translations, so I guess moderators would suggest the best practice if there are to many posts on one topic.

**Comment by ghost** [comment]
By the way, _#12 in the opening post seems like a topic for discussion to me.

If we would want https://habitrpg.com/static/contact fully translated the lines on the page may need some changes, because I'm not sure the respected staff members will be comfortable with receiving many messages in languages from all over the world.

Maybe add something like (we speak English)? E.g.:

## **[Contact Us](https://habitrpg.com/static/contact?lang=en)**

Report Account Problems: admin@habitrpg.com _(English, German) - or no additions in brackets?_
Report a Bug: Github 
Report Community Issues: leslie@habitrpg.com
General Questions about the Site: Newbies Guild
_...and so on..._
**_Please note: we speak English.**_
_General help and support in | language | may be provided by community members in the guild | name |_

@Alys Could you please share you vision?

**Comment by Alys** [comment]
The Contact Us text isn't my call to make, but I personally don't like the "we speak English" text. It seems unfriendly to non-English speakers. I also don't think it's necessary since some of the staff and Tier7+ contributors speak other languages, and have people they can call on for more languages still.

**Comment by lemoness** [comment]
That's true! Between us and our contacts, we speak:

English
Spanish
French
German
Portuguese
Italian
Mandarin
and probably more languages that I don't know about ;)

If we receive something that we really can't understand, we can always
write back with an apology :)

**Comment by ghost** [comment]
@Alys @lemoness Thank you very much! Please excuse me for my suggestion - I didn't mean to doubt the international openness of the team! We feel and highly appreciate your hospitality!

**[Should be solved]** the OP _#12 https://habitrpg.com/static/contact

**Comment by ghost** [comment]
@Atomk in addition to the OP#10
- **[Should be solved]** I've just noticed, that the dialog behind the Send Gift button needs translation too. Please excuse me I've missed it out before. Some lines can be used from previous translations - so it will need some additional time to see what exactly can be reused. I'll look into it tomorrow (it doesn't mean that anyone having time today shouldn't try - just let me know here if you do)

**Comment by hairlessbear** [comment]
@GitHubSphinx [Here](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/options/social/chat-box.jade#L2-5) are a couple more lines that aren't translatable.

**Comment by ghost** [comment]
For the sake of keeping the track of some recent examples:
- Entry level json
  - [x] Examples of text improvements https://github.com/HabitRPG/habitrpg/issues/5262 https://github.com/HabitRPG/habitrpg/pull/5302
  - Some translation strings are not in use anymore https://github.com/HabitRPG/habitrpg/issues/5372
- Entry level jade
  - [x] Html symbols not rendered https://github.com/HabitRPG/habitrpg/issues/5571
  - [ ] Welcoming Community Guidelines warning https://github.com/HabitRPG/habitrpg/issues/4522#issuecomment-109038139
  - [ ] a couple of links aren't translatable https://github.com/HabitRPG/habitrpg/issues/4522#issuecomment-113289466
  - [x] many strings in settings.jade https://github.com/HabitRPG/habitrpg/issues/4522#issuecomment-113379560 - https://github.com/HabitRPG/habitrpg/pull/6055
  - [x] translatable hover text on button https://github.com/HabitRPG/habitrpg/pull/5574
  - [x] 1-8, 10-12 in the opening post here https://github.com/HabitRPG/habitrpg/issues/4522#issue-54472109
  - [x] help text on tasks page should be translatable - https://github.com/HabitRPG/habitrpg/issues/5202 - good examples of including translatable links including [commit](https://github.com/SabreCat/habitrpg/commit/9dc661bb5f1c34d4fd825b22040339166398895a) and [commit](https://github.com/HabitRPG/habitrpg/pull/5350/files)
  - [x] Back to all challenges button caption (when accessing a challenge with a link e.g. from a guild) and (more interesting) making a line more flexible using a variable and an image as a variable https://github.com/HabitRPG/habitrpg/pull/5410
  - [x] Made gift dialog translatable https://github.com/HabitRPG/habitrpg/pull/5292 - examples of using one-time binding https://github.com/HabitRPG/habitrpg/commit/fce9d39f19cb3080e6bca4e1b96e5a7d9ca20ee6
- A bit more tricky jade
  - [x] Gear attributes in stats - ng-repeat case https://github.com/HabitRPG/habitrpg/issues/4522#issuecomment-102659643 https://github.com/HabitRPG/habitrpg/pull/5501
- CoffeeScript
  - [ ] Set names in "Time Travelers" page https://github.com/HabitRPG/habitrpg/issues/4522#issue-54472109 in: [content.coffee](https://github.com/HabitRPG/habitrpg/blob/develop/common/script/content.coffee#L36)
  - [ ] Error message for invalid translation strings https://github.com/HabitRPG/habitrpg/issues/5202#issuecomment-102036171
- JS
  - [ ] The Finish tour, Prev. and Next buttons on Tour https://github.com/HabitRPG/habitrpg/issues/4885#issuecomment-96365837
  - [ ] Messages in the front page Login / Register dialog https://github.com/HabitRPG/habitrpg/issues/4522#issuecomment-101237606 in: [auth.js](https://github.com/HabitRPG/habitrpg/blob/develop/website/src/controllers/auth.js)
  - [ ] System messages in party chat like [when a spell is cast](https://github.com/HabitRPG/habitrpg/blob/develop/website/src/controllers/user.js#L468) - #5757
- Seemingly complex
  - [ ] articles ("a") of food and pets' names are not translatable in [content.coffee](https://github.com/HabitRPG/habitrpg/blob/develop/common/script/content.coffee#L1069) thus [feedPet string](https://github.com/HabitRPG/habitrpg/blob/develop/website/public/js/controllers/inventoryCtrl.js#L125) (`Feed <%= article %><%= text %> to your <%= name %>?`) rendered in [inventoryCtrl.js](https://github.com/HabitRPG/habitrpg/blob/develop/website/public/js/controllers/inventoryCtrl.js#L125)returns a mix of translated text and untranslatable article "a" in the middle. https://github.com/HabitRPG/habitrpg/issues/5639
- Third-party solutions
  - [ ] Calendar when setting due dates for tasks (?)
  - [ ] Share buttons captions https://github.com/HabitRPG/habitrpg/issues/5223
  - [ ] Text of email notifications (?)

**Comment by hairlessbear** [comment]
Two more instances of links that aren't translatable, but should be: [`timeTravelersPopover`](https://github.com/HabitRPG/habitrpg/blob/42d49a923632a34b8e693b258b6a93e292ccf675/common/locales/en/subscriber.json#L67) and [`seasonalShopClosedText`](https://github.com/HabitRPG/habitrpg/blob/39cb9bfb990d883a794cdc4d514aff6765c0b0c8/common/locales/en/limited.json#L26). For any aspiring coders unsure of how to make a link translatable, [#5350](https://github.com/HabitRPG/habitrpg/pull/5350/files) has multiple examples.

**Comment by hairlessbear** [comment]
There are a ton of untranslatable lines in [`settings.jade`](https://github.com/HabitRPG/habitrpg/blob/7a1c5835d0050b79116243af9c4b66691a971d6f/website/views/options/settings.jade). [Item 1](https://github.com/HabitRPG/habitrpg/blob/7a1c5835d0050b79116243af9c4b66691a971d6f/website/views/options/settings.jade#L92), [Item 2](https://github.com/HabitRPG/habitrpg/blob/7a1c5835d0050b79116243af9c4b66691a971d6f/website/views/options/settings.jade#L99), [Item 3](https://github.com/HabitRPG/habitrpg/blob/7a1c5835d0050b79116243af9c4b66691a971d6f/website/views/options/settings.jade#L173), [Item 4](https://github.com/HabitRPG/habitrpg/blob/7a1c5835d0050b79116243af9c4b66691a971d6f/website/views/options/settings.jade#L200), [Items 5 + 6](https://github.com/HabitRPG/habitrpg/blob/7a1c5835d0050b79116243af9c4b66691a971d6f/website/views/options/settings.jade#L204-205), [Item 7](https://github.com/HabitRPG/habitrpg/blob/7a1c5835d0050b79116243af9c4b66691a971d6f/website/views/options/settings.jade#L223), [Item 8](https://github.com/HabitRPG/habitrpg/blob/7a1c5835d0050b79116243af9c4b66691a971d6f/website/views/options/settings.jade#L244), [Item 9](https://github.com/HabitRPG/habitrpg/blob/7a1c5835d0050b79116243af9c4b66691a971d6f/website/views/options/settings.jade#L176), [Item 10](https://github.com/HabitRPG/habitrpg/blob/7a1c5835d0050b79116243af9c4b66691a971d6f/website/views/options/settings.jade#L178), [Items 11 + 12](https://github.com/HabitRPG/habitrpg/blob/7a1c5835d0050b79116243af9c4b66691a971d6f/website/views/options/settings.jade#L180-181), [Items 13 + 14](https://github.com/HabitRPG/habitrpg/blob/7a1c5835d0050b79116243af9c4b66691a971d6f/website/views/options/settings.jade#L255-256), [Item 15](https://github.com/HabitRPG/habitrpg/blob/7a1c5835d0050b79116243af9c4b66691a971d6f/website/views/options/settings.jade#L360), [Item 16](https://github.com/HabitRPG/habitrpg/blob/7a1c5835d0050b79116243af9c4b66691a971d6f/website/views/options/settings.jade#L363), [Item 17](https://github.com/HabitRPG/habitrpg/blob/7a1c5835d0050b79116243af9c4b66691a971d6f/website/views/options/settings.jade#L366), [Items 18-20](https://github.com/HabitRPG/habitrpg/blob/7a1c5835d0050b79116243af9c4b66691a971d6f/website/views/options/settings.jade#L368-370), [Item 21](https://github.com/HabitRPG/habitrpg/blob/7a1c5835d0050b79116243af9c4b66691a971d6f/website/views/options/settings.jade#L221), and finally [Item 22](https://github.com/HabitRPG/habitrpg/blob/7a1c5835d0050b79116243af9c4b66691a971d6f/website/views/options/settings.jade#L391).

**Comment by ksami** [comment]
Hi I'm a new developer. Is there anyone working on this? If not I can take a shot at it.

**Comment by ghost** [comment]
Hi! I believe your help will be much appreciated. Have a look at the
examples above - some of the lines were fixed, but most of them never found
a developer to work on them.

**Comment by ksami** [comment]
Okay, I'll start with settings.jade first to get used to everything.

**Comment by ksami** [comment]
edit: Nevermind I figured it out.
If there is a string like `You have {{user.purchased.plan.extraMonths | number:2}} months of subscription credit.`, should I put the entire string including the `{{` part into the .json file too?

**Comment by ksami** [comment]
[`seasonalShopClosedText`](https://github.com/HabitRPG/habitrpg/blob/bcc522f08d50148f2f44b46d922653966c15daeb/common/locales/en/limited.json#L29) has already been made translatable along with a few other lines in that file.

**Comment by NathanMaton** [comment]
I think this needs to be closed as @crookedneighbor pulled this into https://github.com/HabitRPG/habitrpg/commit/35a921bf43a1d33b0606e622d5ab8fd809d834b1

**Comment by Alys** [comment]
Good point, thanks @NathanMaton!
