### ISSUE TITLE
[Skill Rebalancing March 2015] GitHub Issues and Wiki Pages to update

### ISSUE THREAD

**Issue by chimericdream** [HabitRPG/habitica#4853]
This is a list of issues here on GitHub that should be fixed as a result of the [overhaul to skills](https://github.com/HabitRPG/habitrpg/issues/3029) soon to be made live.

Please comment below if I have missed any issues here or pages on the wiki. I will add them to the list. Also let me know if I added something that is _not_ affected. I haven't had a chance to go through the entire set of code changes, so I may have items below that are not actually part of the update.
### GitHub Issues
- [x] [#3542 - Nerfing Burst of Flames Boss Damage](https://github.com/HabitRPG/habitrpg/issues/3542)
- [x] [#2829 - Backstab description misleading](https://github.com/HabitRPG/habitrpg/issues/2829)
- [x] [#4474 - prevent attribute points being gained above level 100 - related to Skill Rebalancing](https://github.com/HabitRPG/habitrpg/issues/4474)
- [x] [#3029 - Fix Overpowered Skills](https://github.com/HabitRPG/habitrpg/issues/3029)
- [x] [#4473 - missed Dailies reduce MP gained at cron -- related to Skill Rebalancing](https://github.com/HabitRPG/habitrpg/issues/4473)
- [x] [#4412 - Protective Aura (protectAura) Skill Rebalancing](https://github.com/HabitRPG/habitrpg/issues/4412)
- [x] [#3969 - Mana regeneration is only indirectly affected by productivity](https://github.com/HabitRPG/habitrpg/issues/3969)
- [x] [#3353 - 'Stealth' overpowered?](https://github.com/HabitRPG/habitrpg/issues/3353)
### HabitRPG Wiki Pages
- [x] [Character Attributes](http://habitrpg.wikia.com/wiki/Character_Attributes) - May need to be updated if things like crit chance, XP/MP/GP gain, etc are affected by the change
- [x] [Class System](http://habitrpg.wikia.com/wiki/Class_System) - Not sure anything on this page is changing, but it should be reviewed
- [x] [Skills](http://habitrpg.wikia.com/wiki/Skills) - Skills for the different classes (not sure if this is pulled dynamically from the individual pages or not)
- [x] [Warrior](http://habitrpg.wikia.com/wiki/Warrior) - Skills
- [x] [Mage](http://habitrpg.wikia.com/wiki/Mage) - Skills
- [x] [Healer](http://habitrpg.wikia.com/wiki/Healer) - Skills
- [x] [Rogue](http://habitrpg.wikia.com/wiki/Rogue) - Skills
- [x] [Mana Points](http://habitrpg.wikia.com/wiki/Mana_Points) - The section titled "Gaining Mana"

**Comment by lemoness** [comment]
This is incredibly helpful, thank you!

**Comment by Alys** [comment]
The wiki changes required have been documented here: http://habitrpg.wikia.com/wiki/User_blog:LadyAlys/Skills_Rebalancing_and_Other_Changes#comm-36700
Some of the pages listed above include content from other pages, and so not all of them need to be edited manually.

Thank you @chimericdream!

**Comment by Alys** [comment]
All listed issues are closed. Thank you @chimericdream
