### ISSUE TITLE
API v3

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#5984]
This is just for future reference.
- [ ] Remove logging to console where not necessary, maybe output to loggly...
- [ ] Phase out usernames?
- [ ] Validates params for every req
- [ ] Limit sign up to website & trusted apps only?
- [ ] Reorganize indexes and only use the ones really necessary
- [ ] Standard error handling
- [ ] go through all comments, TODOs, FIXMEs
- [ ] Reorganize controllers (separate tasks, user methods from content methods...)
- [ ] Trick to clean memory (`user = group = null...`) not necessary anymore
- [ ] Translate every error string?
- [ ] Standard set of fields to return 
- [ ] Base model class
- [ ] TODOs sorting bug (split into 2 lists)
### History
- [ ] Enable multiple entry dates for task's history, especially for habits (before only one for day)
- [ ] Preen history after 1 year for subscribed users 
- [ ] Preen challenges history https://github.com/HabitRPG/habitrpg/blob/develop/website/src/controllers/user.js#L141-L144
### Lodash 3
- [ ] dotSet & dotGet -> use lodash methods
- [ ] https://github.com/HabitRPG/habitrpg/pull/5976/files#r40495886
### Express 4
- [ ] deprecations https://github.com/HabitRPG/habitrpg/pull/5794
### Cleanup
- [ ] files in /libs or /config from root
- [ ] server.js remove code and put in /libs or /config
- [ ] eslint
- [ ] remove coffee from routes
### Mongoose 4 Optional Features
- [ ] MIGHT BE USEFUL mongoose#1530 (https://github.com/Automattic/mongoose/issues/1530): If you set a field with the 'ref' property to a document whose model name is equal to the 'ref', mongoose will treat the field as if it were .populate()-ed.
- [ ] MIGHT BE USEFUL mongoose#2698 (https://github.com/Automattic/mongoose/issues/2698) Setters are now applied on paths with ref set
- [ ] NEW FEAT mongoose#2138: Query middleware. You can now specify hooks like schema.pre('find') and schema.post('findOne').
- [ ] NEW FEAT mongoose#860: You can optionally run validators and set defaults if a new document is created on update() and findOneAndUpdate() calls. In order to access these features, you must explicitly set the runValidators and setDefaultsOnInsert options when you call update() or findOneAndUpdate(). Note that the setDefaultsOnInsert option is not compatible with MongoDB <= 2.2. Further note update() and findOneAndUpdate() explicitly run validators with a null context (that is, this === null in the validator function).
- [ ] NEW FEAT mongoose#661: Can now specify validators for array elements
##

**Comment by SabreCat** [comment]
Reference for FIXME/TODO: https://github.com/HabitRPG/habitrpg/issues/5542

**Comment by paglias** [comment]
Phase out usernames too
