### ISSUE TITLE
Convert API (v3) Integration tests to use the new `await` syntax

### ISSUE THREAD

**Issue by crookedneighbor** [HabitRPG/habitica#6431]
[This PR illustrates](https://github.com/HabitRPG/habitrpg/pull/6423/files) how to do the conversion.

Notice that each `before/beforeEach/it` blocks callback function has been replaced with `async function`

This allows use to use the `await` keyword to wait for the promise to resolve and it returns the value that the promise resolves with.

tests in test/api/v3/integration in the api-v3-groups branch that need to be converted
#### chat
- [ ] `│   ├── GET-chat.test.js`
- [ ] `│   ├── POST-chat.flag.test.js`
- [ ] `│   ├── POST-chat.like.test.js`
- [ ] `│   └── POST-chat.test.js`
#### groups
- [ ] `│   └── POST-groups.test.js`
#### notFound
- [ ] `├── notFound.test.js`
#### tags
- [ ] `│   ├── DELETE-tags_id.test.js`
- [ ] `│   ├── GET-tags.test.js`
- [ ] `│   ├── GET-tags_id.test.js`
- [ ] `│   ├── POST-tags.test.js`
- [ ] `│   └── PUT-tags_id.test.js`
#### tasks
- [ ] `│   ├── DELETE-tasks_id.test.js`
- [ ] `│   ├── GET-tasks.test.js`
- [ ] `│   ├── GET-tasks_id.test.js`
- [ ] `│   ├── POST-tasks.test.js`
- [ ] `│   ├── POST-tasks_id_score_direction.test.js`
- [ ] `│   ├── PUT-tasks_id.test.js`
#### tasks/checklists
- [ ] `│   │   ├── DELETE-tasks_taskId_checklist_itemId.test.js`
- [ ] `│   │   ├── POST-tasks_taskId_checklist.test.js`
- [ ] `│   │   ├── POST-tasks_taskId_checklist_itemId_score.test.js`
- [ ] `│   │   └── PUT-tasks_taskId_checklist_itemId.test.js`
#### tasks/tags
- [ ] `│       ├── DELETE-tasks_taskId_tags_tagId.test.js`
- [ ] `│       └── POST-tasks_taskId_tags_tagId.test.js`
#### user
- [ ] `├── GET-user.test.js`
#### user/auth
- [ ] `└── POST-register_local.test.js`

**Comment by TheHollidayInn** [comment]
I can get all the group and chat tests converted/created. I am already working on a PR with many group routes, so it would be a simple extension.

**Comment by GeorgeSG** [comment]
I see @TheHollidayInn is taking group & chat tests. I'm doing tags & tasks :)

**Comment by paglias** [comment]
@GeorgeSG hi, can you state exactly what you're going to work on? Converting tests to the new syntax?

**Comment by GeorgeSG** [comment]
@paglias, yup, I'll refactor the tags/tasks tests to use the new syntax.

Unrelated question - the issue description states the tests should be fixed in `api-v3-groups` and not `api-v3` - is this correct?

**Comment by paglias** [comment]
@GeorgeSG yes, it's better if you push to api-v3-groups for now

**Comment by GeorgeSG** [comment]
Just FIY, I also refactored the user tests and the notFound one. PR today or tomorrow :)
