### ISSUE TITLE
API v3 Short-Term Roadmap 1

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#6509]
This is a list of small items regarding the upcoming API v3. If you plan to make a Pull Request just announce it with a comment. We'd like to have _atomic_ PRs so each one should only implement 1 route and its tests, if you plan to do more (awesome!) just propose separate PRs. All PRs must be done against the `api-v3-groups` branch.

**Members**
- [x] tests for getMember route
- [x] option to always populate leader? (on hold)
- [x] route to get members for challenges and tests (assigned to @paglias)

**Groups**
- [x] tests for remove group member route (assigned to @TheHollidayInn, in progress)
- [x] tests for get group route (assigned to @TheHollidayInn, in progress)
- [x] tests for get groups route (assigned to @TheHollidayInn, in progress)
- [x] tests for leave group route (assigned to @TheHollidayInn, in progress)
- [x] tests for join group route (assigned to @KristianTashkov , in progress)

**Challenges**
- [x] Challenge.getChallenge (assigned to @paglias)
- [x] Get challenges for group and tests (assigned to @paglias)
- [x] Update challenge route and tests (assigned to @paglias)
- [x] Challenge export to CSV route and tests (assigned to @paglias)
- [x] Get member progress route and tests (assigned to @paglias)
- [x] join route and tests (assigned to @KristianTashkov)
- [x] leave route and tests (assigned to @KristianTashkov)
- [x] user.unlink (assigned to @paglias)
- [x] tests for select winner route (assigned to @KristianTashkov)
- [x] tests for delete route (assigned to @KristianTashkov)
- [x] tests for create route (assigned to @crookedneighbor)
- [x] tests for get single challenge route
- [x] populate leader and group info

**Chat**
- [x] clearFlagCount route and tests (assigned to @TheHollidayInn)
- [x] seenMessage route and tests (assigned to @TheHollidayInn)
- [x] deleteChatMessage route and tests (assigned to @TheHollidayInn)

**Quest**
- [x] quests/invite route and tests (wip pr #6565)
- [x] quests/accept route and tests (wip pr #6565)
- [x] quests/reject route and tests (wip pr #6640)
- [x] quests/cancel route and tests (wip pr #6654)
- [x] quests/abort route and tests (wip pr #6662)
- [x] quests/leave route and tests (wip pr #6655)

**Tasks**
- [x] clearCompleted todos route and tests
- [x] getTasks route: add ability to get only completed todos (assigned to @paglias)
- [x] fix move task and tests (assigned to @paglias)
- [x] score task: when a todo is un-completed dateCompleted attribute must be removed (assigned to @paglias)
- [x] unlinkTask route (assigned to @paglias)

**Cron**
- [x] decide whether to move code to /src and tests (on hold for now)
- [ ] unit tests

**Unit tests**
- [ ] Group.getGroup
- [ ] challenges methods for access control (canView, canModify, hasAccess, isMember)
- [ ] Tests for challenges tasks routes, sync and user.unlinkChallengesTasks
- [ ] tests for unlinkTask route

**Other**
- [ ] Go though pending tests (on hold) 
- [x] port new history preening (assigned to @paglias)

**Comment by paglias** [comment]
I forgot, all PRs must be done against the `api-v3-groups` branch.

**Comment by GeorgeSG** [comment]
I want to start with something simple, so I think I'll try this one: `tests for get group route` :)

**Comment by paglias** [comment]
@GeorgeSG I may have made an error, I think that one has already been taken by @TheHollidayInn along with the one for getting all groups. I'm sorry, I'll update the issue once I get home

**Comment by paglias** [comment]
@GeorgeSG I've updated the issue, if you wanted to try something simple I'd probably suggest `tests for remove group member route` or `tests for getMember route` but this second one is currently in the `api-v3-members` branch, I'd reccomend the first one since it's in a more stable branch

**Comment by KristianTashkov** [comment]
@paglias reserving Challenges `join` and `leave`. If I take too long with the `join` route, someone can take `leave` :smile_cat:

**Comment by paglias** [comment]
@KristianTashkov great :) I'd do `join` before since there's already the code to sync data to a user (challenge.syncToUser). Note that this method still needs testing so if it doesn't work and the reason of the fail is not obvious or not easy to fix, ignore it (maybe out a TODO) and we'll enable it when it works. Also syncToUser has been rewritten in api-v3-challenges-tasks so you should probably PR against that branch

For `leave` you'll need to implement a method to remove challenge data from the user, the old one that we used in v2 was user.unlink that you can find in the user model

**Comment by TheHollidayInn** [comment]
I'm still working through the groups stuff, but I can continue working on the chat routes as we go. I need to work on them for some tests any way.

**Comment by SabreCat** [comment]
I've been spending so much of my days on architecture and support that I haven't been coding as much as I'd like to, but I'd like to help out with this at least a little. Maybe some of the Quests stuff would be the right size.

**Comment by paglias** [comment]
@SabreCat just assign yourself to one of those items (or to all!) :)
@TheHollidayInn I'll assign you to the chat routes

**Comment by SabreCat** [comment]
Claimed the first one off the list. Hopefully by aiming small I can follow through OK :p

**Comment by SabreCat** [comment]
I have tests almost done for /quest/invite. Could y'all smart people take a look at https://github.com/HabitRPG/habitrpg/pull/6565/files and share thoughts before I get into the route? There's one test I've commented that I'm not sure what the expected result should be, in particular.

**Comment by TheHollidayInn** [comment]
Awesome! I'll take a look in the next few minutes.

**Comment by KristianTashkov** [comment]
@paglias sign me up for the remaining two challenge tasks

**Comment by paglias** [comment]
@KristianTashkov the tests for create and select winner routes?
