### ISSUE TITLE
API v3 Short-Term Roadmap 2

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#6776]
This is a list of work items regarding the upcoming API v3. 

If you plan to make a Pull Request please post a comment to this issue before starting.

We'd like to have atomic PRs as much as possible so each one should implement only one route with the related tests. All PRs must be done against the api-v3` branch.

Items already assigned are marked with the username of the person assigned.

---
# Routes
### Authentication
- [x] Tests for login route (assigned to @piousbox)
- [x] Tests for attaching local authentication to a Facebook user
- [x] Change email / username / password (assigned to @piousbox)
- [x] Reset password (assigned to @piousbox)
- [x] Tests for deleting social authentication (assigned to @piousbox)
- [x] getFirebaseToken (assigned to @paglias)
- [x] setupPassport (assigned to @paglias)
### Other routes
- [x] delete user (along with his tasks and remove from challenges, groups, ...) (assigned to @TheHollidayInn)
- [x] getUserAnonymized (assigned to @piousbox)
- [x] update user (assigned to @crookedneighbor)
- [x] cast (assigned to @paglias)
- [x] sessionPartyInvite (refactor and tests) (assigned to @paglias)
- [x] getBuyList
- [x] getModelPaths (assigned to @paglias)
- [x] user.tmp and user.filters (assigned to @paglias)
### Dev routes (in separate controller)
- [x] add ten gems (assigned to @TheHollidayInn)
- [x] add hour glass (assigned to @TheHollidayInn)
## Content
- [x] getContent (was in user controller in api v2)
## Groups
- [x] reject group invite (assigned to @TheHollidayInn)
## Members (needs refactoring!)
- [x] sendMessage (assigned to @TheHollidayInn)
- [x] sendPrivateMessage (move to inbox routes?) (assigned to @TheHollidayInn)
- [x] sendGift (assigned to @TheHollidayInn)
## Challenges
- [x] tests for /unlink (assigned to @TheHollidayInn)
- [x] unit tests for sync to members (assigned to @TheHollidayInn)
## Tasks
- [x] tests for routes used to manage tasks for challenges (assigned to @TheHollidayInn)
- [x] test task scoring for challenges tasks (assigned to @TheHollidayInn)

**Comment by TheHollidayInn** [comment]
I can take the following if no one else is working on them.
- test task scoring for challenges tasks
- reject group invite
- add ten gems
-  add hour glass

**Comment by paglias** [comment]
@TheHollidayInn sure! Since it's not too clear for "test task scoring for challenges tasks" I meant to test this part of the code https://github.com/HabitRPG/habitrpg/blob/api-v3/website/src/controllers/api-v3/tasks.js#L436

**Comment by TheHollidayInn** [comment]
Perfect! Thanks for clarifying.

**Comment by TheHollidayInn** [comment]
I'll take getContent and all the Members routes if that is okay.

**Comment by paglias** [comment]
@TheHollidayInn let's skip the getContent route for now, the way it works it skips a lot of important data and I want to give it a better look, you can do the delete user instead

**Comment by paglias** [comment]
the members routes are ok
