### ISSUE TITLE
[API v3] Shared code port guide and roadmap

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#6887]
Shared code has been split into multiple files. It has to be adapted to v3 and ported to ES6.

For now we're only going to port _ops_, starting from _user_ ones and ignoring those which handle tasks that'll be done later.

_Libs_ and _fns_ should be modified only when they're used by the op that's being ported, the remaining ones will be reviewed at the end.

The changes should be the following:
- Port code to ES6
- Explicitly declare routes in the API controllers (we don't import all of them at once automatically)
- Only really shared code should stay in /common, anything else (markModified, ...) should be moved where appropriate (server or client)
- Ops/fns shouldn't use callbacks but return values. _NOTE:_ responses should be where possible the same ones as API v2, new properties can be added to existing objects but nothing should be removed. If something needs to be removed post a comment before doing so
- Errors should be thrown (using the classes that can be found into /common/script/libs/errors)
- Where access to the request object (to get parameters or return localized messafeg) is necessary it can be passed as the last object
- The user should be passed like any other parameter, it won't be automatically available anymore
- Fns should behave like ops (throwing errors, returning values, accepting `req` and `user` parameters...)
- Both unit (for shared code) and integration (for api endpoints) tests should be written trying not to duplicate too many tests (the preference is for unit tests)
- Where possible avoid to make breaking changes the API (query parameters, ...)
  An example can be found here https://github.com/HabitRPG/habitrpg/pull/6886
### Ops

Can be found in `/common/script/ops`.
#### User
- [x] `allocate.js` -
- [x] `allocateNow.js` -
- [x] `buy.js` -
- [x] `buyMysterySet.js` -
- [x] `buyQuest.js` -
- [x] `buySpecialSpell.js` -
- [x] `changeClass.js` -
- [x] `disableClasses.js` -
- [x] `equip.js` -
- [x] `feed.js` -
- [x] `hatch.js` -
- [x] `hourglassPurchase.js` - assigned to @TheHollidayInn 
- [x] `openMysteryItem.js` -
- [x] `purchase.js` -
- [x] `readCard.js` -
- [x] `rebirth.js` - Changes tasks
- [x] `releaseBoth.js` -
- [x] `releaseMounts.js` -
- [x] `releasePets.js` -
- [x] `reroll.js` - Changes tasks
- [ ] `reset.js` - Changes tasks
- [x] `revive.js` -
- [x] `sell.js` -
- [x] `sleep.js` -
- [x] `unlock.js` -
- [x] `update.js` - This version is only used on the client, API uses (in v2 too) different code ON HOLD
- [x]  `scoreTask.js` - Missing unit tests
#### Push devices - ON HOLD
- [x] `addPushDevice.js` - API only
#### Tags - API v3 has specific routes for them that use some server specific code, does it make sense to move them back to common code? - ON HOLD
- [x] `addTag.js` -
- [x] `getTag.js` -
- [x] `getTags.js` -
- [x] `updateTag.js` -
- [x] `sortTag.js` -
- [x] `deleteTag.js` -
#### Tasks - API v3 has specific routes for them that use some server specific code, does it make sense to move them back to common code? - ON HOLD
- [x] `addTask.js` -
- [x] `clearCompleted.js` -
- [x] `deleteTask.js` -
- [x] `score.js` - Renamed to `scoreTask.js`. Done, missing unit tests
- [x] `updateTask.js` -
- [x] `sortTask.js` -
#### Webhooks
- [x] `addWebhook.js` -
- [x] `deleteWebhook.js` -
- [x] `updateWebhook.js` -
#### PMs / Inbox - IN PROGRESS
- [x] `clearPMs.js` -
- [x] `deletePM.js` -
- [x] `blockUser.js` -
### Libs ON HOLD

Can be found in `/common/script/libs`.
- [x] `appliedTags.js`
- [x] `gold.js` 
- [x] `silver.js`
- [x] `noTags.js`
- [x] `percent.js`
- [x] `taskClasses.js`
- [ ] `preenTodos.js` - Missing unit tests only
- [x] `splitWhitespace.js` -
- [x] `taskDefaults.js` - Missing unit tests only
- [x] `dotGet.js` - use lodash's `get` method, remove at all if possible
- [x] `dotSet.js` - use lodash's `set` method, remove at all if possible
- [x] `uuid.js` - use `uuid` module `v4` method, remove at all if possible
- [x] `countExists.js` - It's used somewhere? Can't find it in shared or server code and Client has the same code at `$rootScope.countExists`
- [x] `encodeiCalLink.js` - Doesn't seem to be used anywhere
- [x] `friendlyTimestamp.js` - Doesn't seem to be used anywhere
- [x] `newChatMessages.js` - Doesn't seem to be used anywhere
- [x] `preenHistory.js` - Not used anymore, new version can be found at /website/src/libs/api-v3/preening
- [x] `planGemLimits.js` - Convert to ES6 freezing the object or using `const`s
- [x] `removeWhitespace.js` - Doesn't seem to be used anywhere
- [x] `updateStore.js` - Despite what the comment says at the top of the file it's used in the server too - assigned to @paglias
- [x] `refPush.js` -
- [ ] `index.js` - Export all libs, to review at the end
### Fns ON HOLD

Can be found in `/common/script/fns`.
- [ ] `randomDrop.js` - IN PROGRESS
- [x] `crit.js` - 
- [x] `autoAllocate.js -
- [x] `cron.js` - Not used anymore, new version can be found at /website/src/middlewares/api-v3/cron
- [x] `dotGet.js` - Can be removed if we don't pass the user object automatically anymore to fns and ops
- [x] `dotSet.js` - Can be removed if we don't pass the user object automatically anymore to fns and ops
- [x] `getItem.js` - Doesn't seem to be used anywhere
- [x] `handleTwoHanded.js` -
- [x] `nullify.js` - Should not be necessary anymore
- [x] `predictableRandom.js` -
- [x] `preenUserHistory.js` - Not used anymore, new version can be found at /website/src/libs/api-v3/preening
- [x] `randomVal.js` -
- [x] `ultimateGear.js` -
- [x] `updateStats.js` -
- [ ] `index.js` - Review at the end
#### Others
- [ ] `index.js` - Review at the end
### Getters on the user object
- [x] `user.tasks` - maybe keep for client?
- [ ] `user._statsComputed` - convert to method, add unit tests but keep the getter available (it simply call the new method) for backward compatibility
### Helpers already ported to ES6
- [ ] move to appropriate folder (mostly /libs)
