### ISSUE TITLE
a player can incorrectly remain in a quest in a party that they have left

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica#7653]
greeniezona (bf3cdf52-0b87-448a-81dd-459d74323230) reported in the Report a Bug guild:

"I keep randomly losing HP for no reason. I completed all dailies, there was no damage from my party. My suspicion is this damage is from a quest in my old party, a quest and party that I left over a week ago. It shouldn't still be doing damage to me, right?"

That shouldn't be possible but I checked anyway and found this:

greeniezona's current party:

```
{
    "_id": "84bf6664-6bfb-4844-b77a-a5da6dff01c0",
    "quest": {
        "leader": "bf3cdf52-0b87-448a-81dd-459d74323230",
        "members": {
            "bf3cdf52-0b87-448a-81dd-459d74323230": true,
            [and others]
        },
```

greeniezona's previous party:

```
{
    "_id": "c52de31f-2b8d-4da2-8690-148a8d51b944",
    "quest": {
        "leader": "[someone else]",
        "members": {
            [other people]
            "bf3cdf52-0b87-448a-81dd-459d74323230": false,
            [other people]
        },
```

That quest in the previous party was active, even though it had that one false entry in it (must have been force-started by the quest owner).

I have NOT yet had confirmation that the damage from that previous-party quest matches the damage that greeniezona received, but that `false` member value shouldn't be there, regardless.

FYI for Socialites: If you see a player reporting unexplained damage, it could be from:
- negative Habits that they clicked on by accident (mouse might have twitched)
- their own Dailies that weren't marked completed, possibly due to sync errors (Data > Data DIsplay Tool > Dailies History will show if that's happened)
- boss damage from their current party (they can go to the party chat and click "fetch recent messages" to see damage reports)
- this bug (there is no way for a player to work out if they are still in a previous party's quest; an admin will have to search the database to find out)

Actions:
- [x] remove greeniezona from their previous party's quest
- [x] find out how widespread this is - EDIT: 239 players affected
- [x] fix all affected players (Alys will do this today)
- [x] PR #7848 - check that the code for force-starting a quest removes any players from quest.members that don't have a `true` value
- [x] PR #7848 - check that the code for force-starting a quest removes any players from quest.members that aren't in the party
- [x] PR #7845 - check that the code which allows a person to voluntarily leave the party does remove them from the party's quest, regardless of what state the quest is in (confirmed that it does NOT remove them from a pending quest; have not tested an active quest). It must also remove the quest invitation from their own account.
- [x] PR #7849  - check that the code which allows a party leader to boot a member from the party does remove them from the party's quest, regardless of what state the quest is in
- [x] PR #7852 - change the code that allows you to accept/reject a quest invitation so that if you try to do either when you are not in a party, it deletes the invitation (currently it throws an error and you can never reject it
- [x] FIXED IN https://github.com/HabitRPG/habitrpg/pull/7665: adjust the code that allocates quest damage so that it doesn't affect people who don't have a `true` value in `quest.members`. That's only partial mitigation for this bug if a player remains in the quest with a `true` value.
- EDIT: IGNORE: maybe adjust the code that allocates quest damage so that it only damages players after checking that they are also in the party. That would only be worth considering if this turns out to be widespread, and even then might be a bad idea if it results in so many extra queries that it produces other timeouts.
- [ ] anything else?

**Comment by crookedneighbor** [comment]
Thanks for picking this up Alys, I've been meaning to, but haven't had the time. These steps all look correct to me.

**Comment by Alys** [comment]
233 players are in two quests.

6 players are in three quests.

They'll potentially be taking damage from the boss so I'm marking this as high priority, at least until we find out whether the code DOES pass damage on to them from all those quests.

I'm working to remove those players from their excess quests today.

**Comment by Alys** [comment]
FYI for Socialites: There is no way for a player to work out if they are still in a previous party's quest. An admin will have to search the database to find out.

I'm moving this comment up to my first post.

**Comment by Alys** [comment]
greeniezona reports that the damage from the previous-party quest does seem to match the unexplained damage they've been noticing.

**Comment by Alys** [comment]
For all the players who were in two or more quests, I've removed them from the quests in any parties that they were not members of.

There were quite a lot who had `false` or `null` values in group.quest.members for active quests so we definitely need to look for any code that might be permitting that.

It has just this instant occurred to me that there could be players who are in only one quest and yet it's not a quest in their current party. I don't know why that didn't occur to me before. :angry: I'll handle them tomorrow.

**Comment by Alys** [comment]
Based on a new report of this from a user affected by it, it seems that when a player is in an active quest and then leaves the quest and leaves the party, their participation in the quest might be changed from `true` to `false` (the correct behaviour should be that they're deleted from the party's `quest.members` object). That's just a guess at what's happening though; I haven't had time to look at the code.

I'm advertising this in Aspiring Coders in the hope that someone can work on it soon.

Note that I'd be happy if this were fixed in a few different PRs, if it helps to get some fixes done sooner. Anyone who wants to look at this doesn't have to investigate or repair all the code - just fix what you can and I'll use the checklist in the top post to keep track of who's working on what, and what still needs to be done.

**Comment by paglias** [comment]
The group.leave function seems to be missing code that remove the user from the quest participants

This should help

```
        // remove member from quest
        group.quest.members[member._id] = undefined;
        group.markModified('quest.members');
```

**Comment by paglias** [comment]
And also leaving a quest sets the user in `group.quest` to `false` as @Alys thought which still causes damage to be applied because the `group._processBossQuest` method doesn't distinguish between members with `true` or `false` status

**Comment by Alys** [comment]
The code that gives out damage from the boss has been modified so that players won't be damaged if they are listed in the quest.members object as `null` or `false`. This fixes the most urgent issue but the remaining fixes listed in the top post are still needed.

**Comment by Alys** [comment]
Here's another instance of this, where a player is no longer in a party but has a quest invitation, and they can't reject it because the code throws an error about not being able to find the party ID. I had thought that the quest invitation process allowed you to reject a quest invitation no matter what, but I must have been thinking of something else. Tomorrow, I'll search through the database to find all other players affected by that.

Jowker (457488c9-4b52-4f95-ab1a-7b6542db6285) reported this in the bug guild:
"Everytime I access Habiticia I guess the screen for "Quest Invitation: Dilatory Distress, Part 1: Message in a Bottle" I cannot accept or reject cause I get an error with the 'id', I can only press ask later and it keeps coming"

This is their complete party object:

```
    "party": {
        "quest": {
            "key": "dilatoryDistress1",
            "progress": {
                "collectedItems": 0,
                "collect": {},
                "down": 0,
                "up": 0
            },
            "completed": null,
            "RSVPNeeded": true
        },
        "orderAscending": "descending",
        "order": "level"
    },
```

I've deleted their quest invitation.

In the situation where a user who is not in a party tries to EITHER accept or reject a quest invitation, ideally the code should delete the invitation and should not show the user an error message. However after we've fixed the code bugs listed above, it might turn out that this doesn't happen often enough (or at all) for that code change to be worthwhile.

**Comment by Alys** [comment]
1977 users had RSVPneeded set to true but no party ID. I've set RSVPneeded to false for them all, and I've added points to the To-Do list in the top post here to have the code improved for this case too.

**Comment by Alys** [comment]
I checked the database today and about 200 players were still in quests in parties they'd left (about 120 parties). I removed them from those quests.

**Comment by Hus274** [comment]
I'll help work on this!

**Comment by Hus274** [comment]
It doesn't appear that it currently does the following:
-  check that the code for force-starting a quest removes any players from quest.members that don't have a true value

Will look into fixing this first.

**Comment by Hus274** [comment]
[] check that the code which allows a person to voluntarily leave the party does remove them from the party's quest, regardless of what state the quest is in (confirmed that it does NOT remove them from a pending quest; have not tested an active quest). It must also remove the quest invitation from their own account.
should be fixed by #7845

**Comment by Hus274** [comment]
Working on these two:
- check that the code for force-starting a quest removes any players from quest.members that don't have a true value
- check that the code for force-starting a quest removes any players from quest.members that aren't in the party

**Comment by Hus274** [comment]
#7848 should fix the two issues I commented about above.

**Comment by Hus274** [comment]
#7849 -> check that the code which allows a party leader to boot a member from the party does remove them from the party's quest, regardless of what state the quest is in

**Comment by Hus274** [comment]
I'm not sure that this is possible anymore, I'm unable to replicate this issue and I'm not quite sure what to change because I don't know where it's failing.

 change the code that allows you to accept/reject a quest invitation so that if you try to do either when you are not in a party, it deletes the invitation (currently it throws an error and you can never reject it

Any thoughts?

**Comment by Hus274** [comment]
@Alys I know you've been the one primarily doing the research around this, do you think this is still worth doing?

maybe adjust the code that allocates quest damage so that it only damages players after checking that they are also in the party. That would only be worth considering if this turns out to be widespread, and even then might be a bad idea if it results in so many extra queries that it produces other timeouts.

**Comment by Alys** [comment]
@Hus274 Thanks for all the fixes so far! I've updated the list in the top post.

This one still happens:
- "change the code that allows you to accept/reject a quest invitation so that if you try to do either when you are not in a party, it deletes the invitation (currently it throws an error and you can never reject it"

If you add a quest invitation (see below) to a player who isn't in a party, they can't accept or reject. 

```
{ 'party.quest': 
   { RSVPNeeded: true,
     completed: null,
     progress: { collect: {}, down: 0, up: 0 },
     key: 'snake' } }
```

It's not something that can happen normally, but if a bug or erroneous admin change puts an account into that state, the player has no easy way to resolve it. It's low priority, but would be nice for the code to handle it correctly. One of the situations I'm thinking of is that the code base can be used by organisations running their own installs, and we can't control how careful their admins are, so making the code more robust for error conditions makes Habitica look more reliable. But yeah, low priority. Feel free to ignore it if you'd rather move on to something else! 

I think we can forget about this:
- "maybe adjust the code that allocates quest damage so that it only damages players after checking that they are also in the party. That would only be worth considering if this turns out to be widespread, and even then might be a bad idea if it results in so many extra queries that it produces other timeouts."

Your other fixes should prevent that happening and we can tidy up any remaining instances of bad data when your fixes are live.

**Comment by Hus274** [comment]
@Alys awesome, that makes sense. I have to clean up one issue the Blade commented on before but then I should be able to pick that up and finish this one out!

**Comment by Hus274** [comment]
Ok this should be the last one then: #7852

Let me know if there's anything else that should be done here to finish this one out!

**Comment by khipkin** [comment]
@Alys Is this done?

**Comment by Alys** [comment]
Looks like it is! Thanks @Hus274!
