### ISSUE TITLE
Items to-do before group plans launch

### ISSUE THREAD

**Issue by TheHollidayInn** [HabitRPG/habitica#8246]
### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)

- [x] Exclude group tasks where challenge tasks are excluded `'challenge.id': {$exists: false},`
- [ ] Set up group plan email
- [ ] Push amazon worker live

**Comment by librarianmage** [comment]
Should this be closed, as the group plans have already been launched?

**Comment by paglias** [comment]
Let's keep this open for a another few days, still have to do some things
