### ISSUE TITLE
Node 8 Upgrade checklist

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica#9015]
### NPM Install on Node 8 on the node8 branch

```
matteo@macbook~/dev/habitrpg/habitrpg$ npm i
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

├─┬ gulp-nodemon@2.2.1
│ ├─┬ gulp@3.9.1
│ │ └─┬ vinyl-fs@0.3.14
│ │   ├─┬ glob-watcher@0.0.6
│ │   │ └─┬ gaze@0.5.2
│ │   │   └─┬ globule@0.1.0
│ │   │     └─┬ glob@3.1.21
│ │   │       └── graceful-fs@1.2.3
│ │   └── graceful-fs@3.0.11

├─┬ @slack/client@3.16.0
│ └─┬ request@2.76.0
│   └── node-uuid@1.4.8
├─┬ amazon-payments@0.0.4
│ └─┬ request@2.34.0
│   └── node-uuid@1.4.8
└─┬ pusher@1.5.1
  └─┬ request@2.74.0
    └── node-uuid@1.4.8

├─┬ gulp-nodemon@2.2.1
│ ├─┬ gulp@3.9.1
│ │ └─┬ vinyl-fs@0.3.14
│ │   ├─┬ glob-stream@3.1.18
│ │   │ ├─┬ glob@4.5.3
│ │   │ │ └── minimatch@2.0.10  deduped
│ │   │ └── minimatch@2.0.10
│ │   └─┬ glob-watcher@0.0.6
│ │     └─┬ gaze@0.5.2
│ │       └─┬ globule@0.1.0
│ │         ├─┬ glob@3.1.21
│ │         │ └── minimatch@0.2.14  deduped
│ │         └── minimatch@0.2.14
```

### NPM outdated

Package                                   Current         Wanted         Latest   Notes
### Server
- [x] amazon-payments                      0.0.4          0.0.4          0.2.6
- [x] amplitude                            2.0.4          2.0.4          3.5.0     No breaking changes
- [x] nconf                                0.8.5          0.8.5         0.10.0
- [x] passport                             0.3.2          0.3.2          0.4.0
- [x] stripe                              4.25.0         4.25.0          5.4.0
- [x] express                             4.14.1         4.14.1         4.16.2
- [x] csv                                  0.3.7          0.3.7          2.0.0
- [x] csv-stringify                        1.1.2          1.1.2          2.0.1
- [x] cookie-session                       1.3.2          1.3.2   2.0.0-beta.3
- [x] cwait                                1.0.1          1.0.1          1.1.1
- [ ] mongoose                           4.13.10        4.13.10          5.0.3     Has PR
- [ ] js2xmlparser                         1.0.0          1.0.0          3.0.0         Can't get tests to pass
- [ ] validator                            4.9.0          4.9.0          9.4.0
- [ ] express-validator                   2.21.0         2.21.0          4.3.0
- [ ] nodemailer                           2.7.2          2.7.2          4.4.2
- [x] apn                                  1.7.8          1.7.8          2.2.0
- [x] push-notify                          1.2.0            git            git
- [ ] got                                  6.7.1          6.7.1          8.0.3     Should replace request
- [x] moment-recur                         1.0.6            git            git

### Testing/Tooling
- [x] async                                1.5.2          1.5.2          2.6.0     Only used for old migrations, remove
- [x] karma                                1.7.1          1.7.1          2.0.0
- [x] karma-babel-preprocessor             6.0.1          6.0.1          7.0.0
- [x] karma-chai-plugins                   0.6.1          0.6.1          0.9.0
- [x] karma-coverage                       0.5.5          0.5.5          1.1.1
- [x] karma-mocha                          0.2.2          0.2.2          1.3.0
- [x] karma-mocha-reporter                 1.3.0          1.3.0          2.2.5
- [x] karma-sinon-chai                     1.2.4          1.2.4          1.3.3
- [x] karma-spec-reporter                 0.0.24         0.0.24         0.0.32
- [x] gulp                                 4.0.0          4.0.0          3.9.1
- [x] expect.js                            0.2.0          0.2.0          0.3.1
- [x] cross-env                            4.0.0          4.0.0          5.1.3
- [x] cross-spawn                          5.1.0          5.1.0          6.0.4
- [x] coveralls                           2.13.3         2.13.3          3.0.0
- [x] chalk                                1.1.3          1.1.3          2.3.0
- [x] istanbul                     1.1.0-alpha.1  1.1.0-alpha.1          0.4.5
- [x] lcov-result-merger                   1.2.0          1.2.0          2.0.0
- [x] image-size                           0.3.5          0.3.5          0.6.2
- [x] mocha                                3.5.3          3.5.3          5.0.0
- [x] shelljs                              0.7.8          0.7.8          0.8.1
- [x] mongodb                             2.2.34         2.2.34          3.0.2     Removed
- [x] gulp-babel                           6.1.3          6.1.3          7.0.1
- [x] babel-eslint                         7.2.3          7.2.3          8.2.1
- [x] eslint-friendly-formatter            2.0.7          2.0.7          3.0.0
- [x] chai                                 3.5.0          3.5.0          4.1.2 Has PR
- [x] chai-as-promised                     5.3.0          5.3.0          7.1.1 Has PR
- [x] eslint                              3.19.0         3.19.0         4.17.0
- [x] eslint-plugin-html                   2.0.3          2.0.3          4.0.2
- [x] monk                                 4.1.0          4.1.0          6.0.5

### Client Build
- [x] webpack                              2.7.0          2.7.0         3.10.0
- [x] extract-text-webpack-plugin          2.1.2          2.1.2          3.0.2
- [x] webpack-dev-middleware              1.12.2         1.12.2          2.0.4
- [x] vue-loader                          13.7.1         13.7.1         14.1.1
- [x] babel-loader                         6.4.1          6.4.1          7.1.2
- [x] postcss-easy-import                  2.1.0          2.1.0          3.0.0
- [x] svg-inline-loader                    0.7.1          0.7.1          0.8.0
- [x] svgo-loader                          1.2.1          1.2.1          2.1.0
- [x] url-loader                           0.5.9          0.5.9          0.6.2
- [x] autoprefixer                         6.7.7          6.7.7          7.2.5

### Client
- [x] intro.js                             2.7.0          2.7.0  2.8.0-alpha.1
- [x] popper.js                           1.13.0         1.13.0         1.12.9
- [x] bootstrap-vue                        1.5.1          1.5.1     2.0.0-rc.1
- [x] axios                               0.16.2         0.16.2         0.17.1
- [x] axios-progress-bar                   0.1.7          0.1.7          1.1.8
- [x] vuejs-datepicker                    0.9.21            git            git
### Steps
- [x] Remove unused packages

### Todo

- [x] upgrade travis infrastructure
- [x] https://github.com/nodejs/node/issues/16746
- [x] Remove bluebird
- [x] Babel only for import/export transpilation
- [x] Remove bluebird from migrations
- [ ] Upgrade email server
- [ ] http2
- [ ] greenkeeper

**Comment by lemoness** [comment]
@paglias Has this been done?

**Comment by paglias** [comment]
No, I'll do this after the notifications redesign
